### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SKYNISMO** [minis-patchers/SynPotionWeight#1]
System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero. (Parameter 'build')
   at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision)
   at NuGet.Versioning.SemanticVersion..ctor(Int32 major, Int32 minor, Int32 patch)
   at Synthesis.Bethesda.Execution.Patchers.Git.GitPatcherRun.SwapVersioning(XElement proj, String package, String version, SemanticVersion curVersion)
   at Synthesis.Bethesda.Execution.Patchers.Git.GitPatcherRun.ModifyProject(String solutionPath, String drivingProjSubPath, String mutagenVersion, String& listedMutagenVersion, String synthesisVersion, String& listedSynthesisVersion)
   at Synthesis.Bethesda.Execution.Patchers.Git.GitPatcherRun.CheckoutRunnerRepository(String proj, String localRepoDir, GitPatcherVersioning patcherVersioning, NugetVersioningTarget nugetVersioning, Action`1 logger, CancellationToken cancel, Boolean compile)

I'm not very knowledgeable, so what does this mean?

**Comment by SKYNISMO** [comment]
> System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero. (Parameter 'build') at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision) at NuGet.Versioning.SemanticVersion..ctor(Int32 major, Int32 minor, Int32 patch) at Synthesis.Bethesda.Execution.Patchers.Git.GitPatcherRun.SwapVersioning(XElement proj, String package, String version, SemanticVersion curVersion) at Synthesis.Bethesda.Execution.Patchers.Git.GitPatcherRun.ModifyProject(String solutionPath, String drivingProjSubPath, String mutagenVersion, String& listedMutagenVersion, String synthesisVersion, String& listedSynthesisVersion) at Synthesis.Bethesda.Execution.Patchers.Git.GitPatcherRun.CheckoutRunnerRepository(String proj, String localRepoDir, GitPatcherVersioning patcherVersioning, NugetVersioningTarget nugetVersioning, Action`1 logger, CancellationToken cancel, Boolean compile)
> 
> I'm not very knowledgeable, so what does this mean?

all working now, I just put it "match" instead of "latest"

**Comment by Minizbot2012** [comment]
I really, really need to work on these sometime soon to get them updated to newer synthesis / mutagen, but I don't have skyrim installed at the moment, and work keeps piling up on me at this time.
